/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ANCHOR_PROVIDE_KEY: typeof import('@arco-design/web-vue')['NCHOR_PROVIDE_KEY']
  const AS: typeof import('@arco-design/web-vue')['S']
  const AT: typeof import('@arco-design/web-vue')['T']
}
