/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    CloseButton: typeof import('./src/components/CloseButton/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
