import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import pinia from './store';
import '@/assets/styles/base.less';
import '@/assets/styles/font.less';
import ArcoVue from '@arco-design/web-vue';
import ArcoVueIcon from '@arco-design/web-vue/es/icon';
import '@arco-design/web-vue/dist/arco.css';
import 'virtual:svg-icons-register';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';

const app = createApp(App);
app.use(pinia);
app.use(router);
app.use(ArcoVue);
app.use(ArcoVueIcon);
app.use(ElementPlus);
app.mount('#app');
